# Generated by Django 4.1.4 on 2022-12-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.TextField()),
                ('pilotName', models.TextField()),
                ('pilotEmail', models.TextField()),
                ('pilotPhone', models.TextField()),
                ('positionX', models.FloatField()),
                ('positionY', models.FloatField()),
                ('closestTo', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('violatingNDZ', models.BooleanField()),
                ('lastViolated', models.FloatField()),
            ],
        ),
    ]
